name = "GiacSlate"
uuid = "f4c9f34b-fa6a-4506-9309-e8c0bac809fa"
version = "0.1.0"
authors = ["Kahli Burke <kahli@kahliburke.com>"]

[deps]
Giac = "e4421f97-9838-4fd0-9fa5-94f11373bf78"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Giac = "0.14.1"
JSON = "1.6.1"
